FROM python:3.12.14-slim-bookworm

WORKDIR /app

ADD --checksum=sha256:3555bcfd670e134e8360ad934cb5bad1bbe2a7dad24ba7cafa0a3bb8b23c6444 \
    https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/0.1.0.tar.gz \
    /tmp/app.tar.gz

RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /app && rm /tmp/app.tar.gz
RUN pip install --no-cache-dir -r requirements.txt
RUN mv templates_example templates

CMD ["python", "main.py"]
