ARG BASE_IMAGE=python:3.12.14-slim-bookworm
FROM ${BASE_IMAGE}

ARG APP_VERSION=main

WORKDIR /app

ADD https://github.com/MrDave/StaticJinjaPlus/archive/${APP_VERSION}.tar.gz /tmp/app.tar.gz
RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /app && rm /tmp/app.tar.gz

RUN pip install --no-cache-dir -r requirements.txt
RUN mv templates_example templates || true

CMD ["python", "main.py"]
