FROM python:3.12.14-slim-bookworm

WORKDIR /app

ADD --checksum=sha256:30d9424df1eddb73912b0e2ad5375fa2c876c8e30906bec91952dfb75dcf220b \
    https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/0.1.1.tar.gz \
    /tmp/app.tar.gz

RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /app && rm /tmp/app.tar.gz
RUN pip install --no-cache-dir -r requirements.txt
RUN mv templates_example templates

CMD ["python", "main.py"]
